name 'mediawiki'
maintainer 'Manish Sethi'
maintainer_email 'manish@sethis.in'
license 'All rights reserved'
description 'Installs/Configures mediawiki'
long_description 'Installs/Configures mediawiki'
version '0.1.2'
depends 'mysql'
depends 'database'
depends 'apache2'
depends 'php'
supports 'centos'
supports 'rhel'
